### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by ernewton** [mjfields/cosi#4]
![Screen Shot 2021-02-26 at 4 20 03 PM](https://user-images.githubusercontent.com/4790228/109356753-24cb8800-784f-11eb-9f5e-cdf3ff58c228.png)

**Comment by awmann** [comment]
I think this is the older version of emcee that doesn't support progress bar.

**Comment by mjfields** [comment]
Looks like emcee>=3.00 has progress bars. Also what version of python are you using? I'm not sure if this is also a python version issue.

**Comment by mjfields** [comment]
Ok I think the code will now work as it is in the notebook for emcee<3.0. Updating emcee is probably the simplest way to solve this issue, so this is probably overkill, but I wanted to make sure it would work anyway just in case.
