### ISSUE TITLE
problem with upper limit

### ISSUE THREAD

**Issue by awmann** [mjfields/cosi#5]
On line 74 of core.py you have:
        if cvsini > self.vsini:
            return -np.inf

I think this is ONLY supposed to execute if you have an upper limit vsini. Basically, this rejects any solution where Veq > Vsini. But in reality, Vsini has some errors and many Veq>Vsini values are allowed. This would only be the case if Vsini were reported as an upper limit. I think the relevant part of the IDL code has this:
  if keyword_set(upperlimitvsini) then begin
    if cvsini gt vsini then return, !values.d_infinity
  endif

which does make it only apply if vsini is an upper limit. 

I believe that fixes the major problem.

**Comment by awmann** [comment]
Note that the fix is just to add 
"if <some kind of thing that checks if vsini is an upper limit>:"
to right above this test.

**Comment by mjfields** [comment]
To clarify, in the original IDL code it says:

```
if 1- keyword_set(upperlimitvsini) then begin
    chisq = (vsini - cvsini)^2/uvsini^2 + (mrstar - rstar)^2/urstar^2 + (mprot - prot)^2/uprot^2
endif

if keyword_set(upperlimitvsini) then begin
   chisq = (mrstar - rstar)^2/urstar^2 + (mprot - prot)^2/uprot^2
endif
```

So here if vsini is an upper limit, should I remove it from the chisq like in the above IDL code? This would be in addition to what you mentioned before.

**Comment by awmann** [comment]
the top should be if upperlimitvsini is not true, (i.e., the Vsini is not a limit) the bottom should be if it is set (i.e, the provided Vsini is just an upper limit).

**Comment by mjfields** [comment]
Ok this fix should be reflected in the code now.
